# Generated by Django 6.0.7 on 2026-08-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(blank=True, help_text='Deprecated: use StudentEnrollment for historical, session-based placement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deprecated_students', to='academics.schoolclass'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('LEFT', 'Left'), ('TRANSFERRED', 'Transferred'), ('REPEATED', 'Repeated'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.schoolclass')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-date_joined', 'student__last_name', 'student__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_subjects', to='academics.classsubject')),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='students.studentenrollment')),
            ],
            options={
                'ordering': ['student_enrollment__student__last_name', 'student_enrollment__student__first_name', 'class_subject__subject__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'session'), name='unique_student_session_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='studentsubject',
            constraint=models.UniqueConstraint(fields=('student_enrollment', 'class_subject'), name='unique_student_subject_per_enrollment'),
        ),
    ]
