# Generated by Django 6.0.7 on 2026-08-06 14:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Heading for the section.', max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Optional supporting line for this section.', max_length=300, verbose_name='Subtitle')),
                ('body', models.TextField(blank=True, help_text='Main textual content for the section.', verbose_name='Body')),
                ('button_text', models.CharField(blank=True, help_text='Optional call-to-action button label.', max_length=100, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, help_text='Optional destination for the call-to-action button.', max_length=300, verbose_name='Button URL')),
                ('section_type', models.CharField(choices=[('WELCOME', 'Welcome'), ('HIGHLIGHTS', 'Highlights'), ('WHY_CHOOSE_US', 'Why Choose Us'), ('PROGRAMMES', 'Programmes'), ('FACILITIES', 'Facilities'), ('CTA', 'Call to Action'), ('FAQ_PREVIEW', 'FAQ Preview'), ('CONTACT_PREVIEW', 'Contact Preview')], help_text='Type of section this content belongs to on the homepage.', max_length=30, verbose_name='Section type')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order of this section on the homepage.', verbose_name='Display order')),
                ('published', models.BooleanField(default=False, help_text='Only published sections appear on the public homepage.', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Heading for the news or event item.', max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier for this item.', max_length=250, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, help_text='Short summary shown on the news listing.', max_length=400, verbose_name='Summary')),
                ('content', models.TextField(blank=True, help_text='Full body content for the article or announcement.', verbose_name='Content')),
                ('featured_image', models.FileField(blank=True, help_text='Optional image or attachment for the item.', null=True, upload_to='news/', verbose_name='Featured image')),
                ('published', models.BooleanField(default=False, help_text='Only published items appear publicly.', verbose_name='Published')),
                ('featured', models.BooleanField(default=False, help_text='Featured items can be highlighted on the news page.', verbose_name='Featured')),
                ('publish_date', models.DateTimeField(blank=True, help_text='Date and time the item should be considered published.', null=True, verbose_name='Publish date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-publish_date', '-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, help_text='The public name shown across the website.', max_length=200, verbose_name='School name')),
                ('short_name', models.CharField(blank=True, help_text='A shorter name used in compact navigation or headings.', max_length=100, verbose_name='Short name')),
                ('motto', models.CharField(blank=True, help_text='A short slogan or guiding statement for the school.', max_length=250, verbose_name='Motto')),
                ('primary_phone', models.CharField(blank=True, help_text='Primary public contact phone number.', max_length=30, verbose_name='Primary phone')),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary public contact phone number.', max_length=30, verbose_name='Secondary phone')),
                ('email', models.EmailField(blank=True, help_text='Primary public email address.', max_length=254, verbose_name='Email address')),
                ('address', models.TextField(blank=True, help_text='Postal or physical address for the school.', verbose_name='Address')),
                ('office_hours', models.CharField(blank=True, help_text='General office hours shown on the public site.', max_length=250, verbose_name='Office hours')),
                ('hero_title', models.CharField(blank=True, help_text='Main headline displayed on the home page hero section.', max_length=250, verbose_name='Hero title')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Supporting text displayed under the hero title.', max_length=400, verbose_name='Hero subtitle')),
                ('footer_text', models.TextField(blank=True, help_text='Text shown in the global website footer.', verbose_name='Footer text')),
                ('facebook_url', models.URLField(blank=True, help_text='Public Facebook page URL.', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Public Instagram profile URL.', verbose_name='Instagram URL')),
                ('x_url', models.URLField(blank=True, help_text='Public X/Twitter profile URL.', verbose_name='X URL')),
                ('youtube_url', models.URLField(blank=True, help_text='Public YouTube channel URL.', verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Public LinkedIn profile URL.', verbose_name='LinkedIn URL')),
                ('default_meta_description', models.CharField(blank=True, help_text='Fallback meta description for public pages.', max_length=300, verbose_name='Default meta description')),
                ('logo', models.FileField(blank=True, help_text='Optional logo file for the public website.', null=True, upload_to='site/logo/', verbose_name='Logo')),
                ('favicon', models.FileField(blank=True, help_text='Optional favicon file for the public website.', null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('hero_image', models.FileField(blank=True, help_text='Optional hero image file for the website homepage.', null=True, upload_to='site/hero/', verbose_name='Hero image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name displayed on the public website.', max_length=200, verbose_name='Full name')),
                ('slug', models.SlugField(blank=True, help_text="Unique URL-friendly identifier generated from the staff member's name.", max_length=220, unique=True, verbose_name='Slug')),
                ('role', models.CharField(help_text="The staff member's role within the school (for example: Teacher, Librarian, Accountant).", max_length=150, verbose_name='Role')),
                ('is_management', models.BooleanField(default=False, help_text='Indicates whether this staff member should appear on the public management page.', verbose_name='Management team')),
                ('management_position', models.CharField(blank=True, help_text='Management title displayed publicly (for example: Principal or Vice Principal). Leave blank for non-management staff.', max_length=150, verbose_name='Management position')),
                ('biography', models.TextField(blank=True, help_text='Short biography or profile shown on the public website.', verbose_name='Biography')),
                ('photo', models.ImageField(blank=True, help_text='Optional profile photograph.', null=True, upload_to='staff/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, help_text='Optional public contact email.', max_length=254, verbose_name='Email address')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('featured', models.BooleanField(default=False, help_text='Featured staff may appear on the homepage.', verbose_name='Featured')),
                ('published', models.BooleanField(default=False, help_text='Only published staff profiles appear on the public website.', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['display_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The page title shown in the admin and on the public page when used.', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier for this page.', max_length=200, unique=True, verbose_name='Slug')),
                ('navigation_title', models.CharField(blank=True, help_text='Short title used in navigation when needed.', max_length=100, verbose_name='Navigation title')),
                ('hero_title', models.CharField(blank=True, help_text='Main headline for the page hero section.', max_length=250, verbose_name='Hero title')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Supporting text shown beneath the hero title.', max_length=400, verbose_name='Hero subtitle')),
                ('content', models.TextField(blank=True, help_text='Main editable body content for this page.', verbose_name='Page content')),
                ('seo_title', models.CharField(blank=True, help_text='Optional browser and search title override.', max_length=200, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, help_text='Optional meta description for this page.', max_length=300, verbose_name='SEO description')),
                ('published', models.BooleanField(default=False, help_text='Only published pages should appear publicly.', verbose_name='Published')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls ordering for page lists and navigation.', verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Page',
                'verbose_name_plural': 'Website Pages',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
