# Generated by Django 6.0.7 on 2026-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, help_text='The public name shown across the website.', max_length=200, verbose_name='School name')),
                ('short_name', models.CharField(blank=True, help_text='A shorter name used in compact navigation or headings.', max_length=100, verbose_name='Short name')),
                ('motto', models.CharField(blank=True, help_text='A short slogan or guiding statement for the school.', max_length=250, verbose_name='Motto')),
                ('primary_phone', models.CharField(blank=True, help_text='Primary public contact phone number.', max_length=30, verbose_name='Primary phone')),
                ('secondary_phone', models.CharField(blank=True, help_text='Secondary public contact phone number.', max_length=30, verbose_name='Secondary phone')),
                ('email', models.EmailField(blank=True, help_text='Primary public email address.', max_length=254, verbose_name='Email address')),
                ('address', models.TextField(blank=True, help_text='Postal or physical address for the school.', verbose_name='Address')),
                ('office_hours', models.CharField(blank=True, help_text='General office hours shown on the public site.', max_length=250, verbose_name='Office hours')),
                ('hero_title', models.CharField(blank=True, help_text='Main headline displayed on the home page hero section.', max_length=250, verbose_name='Hero title')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Supporting text displayed under the hero title.', max_length=400, verbose_name='Hero subtitle')),
                ('footer_text', models.TextField(blank=True, help_text='Text shown in the global website footer.', verbose_name='Footer text')),
                ('facebook_url', models.URLField(blank=True, help_text='Public Facebook page URL.', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Public Instagram profile URL.', verbose_name='Instagram URL')),
                ('x_url', models.URLField(blank=True, help_text='Public X/Twitter profile URL.', verbose_name='X URL')),
                ('youtube_url', models.URLField(blank=True, help_text='Public YouTube channel URL.', verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Public LinkedIn profile URL.', verbose_name='LinkedIn URL')),
                ('default_meta_description', models.CharField(blank=True, help_text='Fallback meta description for public pages.', max_length=300, verbose_name='Default meta description')),
                ('logo', models.FileField(blank=True, help_text='Optional logo file for the public website.', null=True, upload_to='site/logo/', verbose_name='Logo')),
                ('favicon', models.FileField(blank=True, help_text='Optional favicon file for the public website.', null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('hero_image', models.FileField(blank=True, help_text='Optional hero image file for the website homepage.', null=True, upload_to='site/hero/', verbose_name='Hero image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
