# Generated by Django 6.0.7 on 2026-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The page title shown in the admin and on the public page when used.', max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier for this page.', max_length=200, unique=True, verbose_name='Slug')),
                ('navigation_title', models.CharField(blank=True, help_text='Short title used in navigation when needed.', max_length=100, verbose_name='Navigation title')),
                ('hero_title', models.CharField(blank=True, help_text='Main headline for the page hero section.', max_length=250, verbose_name='Hero title')),
                ('hero_subtitle', models.CharField(blank=True, help_text='Supporting text shown beneath the hero title.', max_length=400, verbose_name='Hero subtitle')),
                ('content', models.TextField(blank=True, help_text='Main editable body content for this page.', verbose_name='Page content')),
                ('seo_title', models.CharField(blank=True, help_text='Optional browser and search title override.', max_length=200, verbose_name='SEO title')),
                ('seo_description', models.CharField(blank=True, help_text='Optional meta description for this page.', max_length=300, verbose_name='SEO description')),
                ('published', models.BooleanField(default=False, help_text='Only published pages should appear publicly.', verbose_name='Published')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls ordering for page lists and navigation.', verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Page',
                'verbose_name_plural': 'Website Pages',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
