# Generated by Django 6.0.7 on 2026-08-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_websitepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Heading for the section.', max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='Optional supporting line for this section.', max_length=300, verbose_name='Subtitle')),
                ('body', models.TextField(blank=True, help_text='Main textual content for the section.', verbose_name='Body')),
                ('button_text', models.CharField(blank=True, help_text='Optional call-to-action button label.', max_length=100, verbose_name='Button text')),
                ('button_url', models.CharField(blank=True, help_text='Optional destination for the call-to-action button.', max_length=300, verbose_name='Button URL')),
                ('section_type', models.CharField(choices=[('WELCOME', 'Welcome'), ('HIGHLIGHTS', 'Highlights'), ('WHY_CHOOSE_US', 'Why Choose Us'), ('PROGRAMMES', 'Programmes'), ('FACILITIES', 'Facilities'), ('CTA', 'Call to Action'), ('FAQ_PREVIEW', 'FAQ Preview'), ('CONTACT_PREVIEW', 'Contact Preview')], help_text='Type of section this content belongs to on the homepage.', max_length=30, verbose_name='Section type')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order of this section on the homepage.', verbose_name='Display order')),
                ('published', models.BooleanField(default=False, help_text='Only published sections appear on the public homepage.', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
