# Generated by Django 6.0.7 on 2026-08-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homepagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Heading for the news or event item.', max_length=250, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Unique URL-friendly identifier for this item.', max_length=250, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, help_text='Short summary shown on the news listing.', max_length=400, verbose_name='Summary')),
                ('content', models.TextField(blank=True, help_text='Full body content for the article or announcement.', verbose_name='Content')),
                ('featured_image', models.FileField(blank=True, help_text='Optional image or attachment for the item.', null=True, upload_to='news/', verbose_name='Featured image')),
                ('published', models.BooleanField(default=False, help_text='Only published items appear publicly.', verbose_name='Published')),
                ('featured', models.BooleanField(default=False, help_text='Featured items can be highlighted on the news page.', verbose_name='Featured')),
                ('publish_date', models.DateTimeField(blank=True, help_text='Date and time the item should be considered published.', null=True, verbose_name='Publish date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Item',
                'verbose_name_plural': 'News Items',
                'ordering': ['-publish_date', '-created_at', 'title'],
            },
        ),
    ]
