# Generated by Django 6.0.7 on 2026-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name displayed on the public website.', max_length=200, verbose_name='Full name')),
                ('slug', models.SlugField(blank=True, help_text="Unique URL-friendly identifier generated from the staff member's name.", max_length=220, unique=True, verbose_name='Slug')),
                ('position', models.CharField(help_text='Leadership or staff position displayed publicly.', max_length=150, verbose_name='Position')),
                ('biography', models.TextField(blank=True, help_text='Short biography or profile shown on the public website.', verbose_name='Biography')),
                ('photo', models.ImageField(blank=True, help_text='Optional profile photograph.', null=True, upload_to='staff/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, help_text='Optional public contact email.', max_length=254, verbose_name='Email address')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('featured', models.BooleanField(default=False, help_text='Featured staff may appear on the homepage.', verbose_name='Featured')),
                ('published', models.BooleanField(default=False, help_text='Only published staff profiles appear on the public website.', verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
